spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/focus_group
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: false
  flyway:
    baselineOnMigrate: true
    validate-migration-naming: true
  mail:
    host: smtp.yandex.ru
    port: 587
    username: AGAIIIA@yandex.ru
    password: effbhfyeelmswlrl
    properties:
      smtp:
        auth: false
        starttls:
          enable: true

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 день - изменить
      refresh-token:
        expiration: 604800000 # 7 дней - изменить

server:
  error:
    include-stacktrace: never